version: '2'
 
services:
  app1:
    build:
      context:  ./app1
      dockerfile: Dockerfile
 
    volumes:
      - data_web:/usr/local/apache2/htdocs/

  app2:
    build:
      context:  ./app2
      dockerfile: Dockerfile
  
    volumes:
      - data_web:/usr/local/apache2/htdocs/

  app3:
    build:
      context:  ./app3
      dockerfile: Dockerfile

    volumes:
      - data_web:/usr/local/apache2/htdocs/
  
  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    links:
      - app1
      - app2
      - app3
    volumes:
      - data_nginx:/etc/nginx/
volumes:
   data_web:
   data_nginx:
