version: '2'
 
services:
  app1:
    build:
      context:  ./app1
      dockerfile: Dockerfile

  app2:
    build:
      context:  ./app2
      dockerfile: Dockerfile

  app3:
    build:
      context:  ./app3
      dockerfile: Dockerfile
 
  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    links:
      - app1
      - app2
      - app3


